name: Releaser

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  debian-release_x64:
    runs-on: ubuntu-latest
    container:
      image: debian:12
      options: --privileged
    steps:

      - name: Git fix
        run: apt-get update && apt-get install -y git sudo

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install live-build
        run: sudo apt-get update && sudo apt-get install -y live-build

      - name: Build
        run: cd debian && sudo ./start.sh

      - name: Checksum
        run: cd debian && checksum=$(md5sum nucleus-amd64.iso) && echo "$checksum" > nucleus.md5 && sed -i "s/^# <checksum placeholder>$/# $checksum/" CHANGELOG.md

      - name: Split
        run: cd debian && split -b 2000m nucleus-amd64.iso nucleus-amd64_part --suffix-length=1 --numeric-suffixes=1 --additional-suffix=.zip

      - name: Version
        id: tag
        run: echo "release_name=NucleusOS-x64_$(date +'%d.%m.%Y-%Hh%M')_debian-based" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.release_name }}
          name: ${{ steps.tag.outputs.release_name }}
          body_path: debian/CHANGELOG.md
          files: |
            debian/nucleus-amd64_part*
            debian/nucleus.md5
          fail_on_unmatched_files: true
          make_latest: true

